skos:
  distributie_pad: ../resources/be/vlaanderen/bodemenondergrond/data/id/conceptscheme/xyzmethode/
  distributie_naam: xyzmethode
  jsonld_source: ../resources/source/codelijst_context.json
  csv_source: ../resources/source/codelijst_source.csv
dcat:
  distributie_pad_catalog: ../resources/be/vlaanderen/bodemenondergrond/data/id/catalog/codelijst-xyzmethode/
  distributie_pad_dataset: ../resources/be/vlaanderen/bodemenondergrond/data/id/dataset/codelijst-xyzmethode/
  jsonld_source : ../resources/source/catalog_context.json
  dataset_source : ../resources/source/dataset_source.csv
  catalog_source : ../resources/source/catalog_source.csv
